import fnmatch
import os

def get_all_files_at(path):
    files = []
    for root, dirnames, filenames in os.walk(path):
      for filename in fnmatch.filter(filenames, '*.cpp'):
          files.append(os.path.join(root, filename))
    return files

def get_objects_at(paths):
    return [Object(get_all_files_at(path)) for path in paths]

def build_project_with_tests(output, sources):
    main_test_object = Object('tests/test.cpp')
    inputs = get_objects_at(sources) + [main_test_object]
    Program(output, inputs, LIBS=['gtest', 'pthread'])

build_project_with_tests('tests/commons_test', ['common/src', 'common/tests'])
build_project_with_tests('tests/bob_test', ['common/src', 'bob/src', 'bob/tests'])
